# This is your main playbook you will run with:
# ansible-playbook site.yml
# You can kick off everything from this playbook.
# Or, you can create separate playbooks in this directory for specific orchestration events.

---
- name: apply common configuration to all nodes
  hosts: suecyde
  gather_facts: false
  become: yes

  roles:
    #    - amd-gpu-setup
    - backlight
    - directory-setup
    - display-manager-sddm
    - essential-setup
    #    - fancontrol
    #    - gpu-passthru
    - i3-setup
    - pacman-packages
    - polybar
    - qemu-setup
    - terminal-setup-alacritty
    - xorg-setup
